services:

  postgres:
    image: postgres:latest
    container_name: auction-service-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs-server-bucket
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUSTFS_ACCESS_KEY=${S3_ACCESS_KEY}
      - RUSTFS_SECRET_KEY=${S3_SECRET_KEY}
      - RUSTFS_VOLUMES=/data
      - RUSTFS_CONSOLE_ENABLE=true
    volumes:
      - ./rustfs-data:/data

  rustfs-init:
      image: minio/mc:latest
      container_name: rustfs-init
      depends_on:
        - rustfs
      entrypoint: >
        /bin/sh -c "
        until mc alias set meu-storage http://rustfs:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY}; do
          sleep 1;
        done;
        mc mb --ignore-existing meu-storage/${S3_BUCKET_NAME};
        mc anonymous set public meu-storage/${S3_BUCKET_NAME};
        "