spring:
  application:
    name: auctionService

  config:
    import: "optional:file:.env[.properties]"

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop

  s3:
    endpoint: ${S3_ENDPOINT}
    bucket-name: ${S3_BUCKET_NAME}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ${S3_REGION}

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: auction-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: org.infnet.auctionservice.*
        spring.json.add.type.headers: false
        spring.json.use.type.headers: false

integrations:
  user-service:
    base-url: http://localhost:8087

app:
  kafka-topics:
    #publiher
      auction-created-pending: "auctions.lot.created-pending"
      auction-approved: "auctions.lot.approved"
      auction-rejected: "auctions.lot.rejected"
      auction-ended-without-winner: "auctions.lot.ended-without-winner"
      auction-ended-with-winner: "auctions.lot.ended-with-winner"
      auction-clicked: "auctions.lot.clicked"
      auction-removed: "auctions.lot.removed"
      auction-renewed: "auctions.lot.renewed"
      auction-canceled: "auctions.lot.canceled"
      bid-highest-invalidated: "auctions.bid.new-highest-assigned"
      bid-placed: "auctions.bid.placed"
      #consumer
      review-rejected: "reviews.auction.rejected"
      review-approved: "reviews.auction.approved"
      transaction-payment-fail: "transactions.status.closed-payment-failed"
      transaction-delivery-fail: "transactions.status.closed-delivery-inactive"
      user-deleted: "users.account.deleted"
      user-suspended: "users.account.suspended"
      user-banned: "users.account.banned"
      user-created: "users.account.created"


