### ==========================================
### VARIÁVEIS GLOBAIS E SIMULAÇÃO DO GATEWAY
### ==========================================
@baseUrl = http://localhost:8080

# 👤 User 1 - Vendedor Principal (Ativo)
@user1_id = bddfe29d-3bd1-47e5-bf4b-03a50c65d534
@user1_name = Nicholas Puggian
@user1_email = rodrigo.cloureiro@al.infnet.edu.br
@user1_allowed = true

# 👤 User 2 - Comprador e Vendedor (Ativo)
@user2_id = 51bd71ce-a60e-40cb-84ff-998688f9acdb
@user2_name = Guilherme Pirozi
@user2_email = rodrigo.cloureiro@al.infnet.edu.br
@user2_allowed = true

# 🚫 User 3 - Usuário Banido/Bloqueado
@user3_id = 64c58708-95cf-4859-aa16-bf1c6c880f7e
@user3_name = Jair M. Bolsonaro
@user3_email = rodrigo.cloureiro@al.infnet.edu.br
@user3_allowed = false


### ==========================================
### 1. ROTAS PÚBLICAS (Sem Headers do Gateway)
### ==========================================

### 🟢 Listar todos os anúncios ativos
GET {{baseUrl}}/auctions/

### 🟢 Buscar informações de um anúncio específico
GET {{baseUrl}}/auctions/1


### ==========================================
### 2. CRIAÇÃO DE ANÚNCIOS (Requer Allowed = true)
### ==========================================

### 🔵 Criar anúncio (Usuário 1) - Completo
POST {{baseUrl}}/auctions/create
X-User-Id: {{user1_id}}
X-User-Name: {{user1_name}}
X-User-Email: {{user1_email}}
X-User-Allowed: {{user1_allowed}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "title": "Pen Drive de Barata 12KB",
  "description": "Sobrevive ao apocalipse nazista nuclear fazendo sexo no camarote com muito novo",
  "category": "ELECTRONICS",
  "initialBidPrice": 10.00,
  "buyNowPrice": 200.00,
  "durationInDays": 3
}
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="pen_drive_barata.jpg"
Content-Type: image/jpeg

< ./images/pen_drive_barata.jpg
--WebAppBoundary--


### 🔵 Criar anúncio (Usuário 1) - Sem BuyNowPrice
POST {{baseUrl}}/auctions/create
X-User-Id: {{user1_id}}
X-User-Name: {{user1_name}}
X-User-Email: {{user1_email}}
X-User-Allowed: {{user1_allowed}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "title": "Olhos Escarlate",
  "description": "Removidos de vítimas do massacre ao clã Kurta pela Troupe Fantasma.",
  "initialBidPrice": 100000.00,
  "category": "COLLECTIBLES_AND_ART",
  "durationInDays": 3
}
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="olhos-escarlate.jpg"
Content-Type: image/jpeg

< ./images/olhos-escarlate.jpg
--WebAppBoundary--


### 🔵 Criar anúncio (Usuário 2)
POST {{baseUrl}}/auctions/create
X-User-Id: {{user2_id}}
X-User-Name: {{user2_name}}
X-User-Email: {{user2_email}}
X-User-Allowed: {{user2_allowed}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
    "title": "LP Leno Brega 1989",
    "description": "LP DISCO DE VINIL LENO BREGA - VOLUME 2, BOM ESTADO GERAL!!!",
    "initialBidPrice": 200.00,
    "buyNowPrice": 500.00,
    "category": "MUSIC",
    "durationInDays": 7
}
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="leno.jpg"
Content-Type: image/jpeg

< ./images/leno.jpg
--WebAppBoundary--


### 🔴 TENTATIVA FALHA: Criar anúncio com Usuário Bloqueado (Deve retornar 403 Forbidden)
POST {{baseUrl}}/auctions/create
X-User-Id: {{user3_id}}
X-User-Name: {{user3_name}}
X-User-Email: {{user3_email}}
X-User-Allowed: {{user3_allowed}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "title": "Produto do Usuário Bloqueado",
  "description": "Não deve ser salvo",
  "initialBidPrice": 100.00,
  "category": "OTHER",
  "durationInDays": 3
}
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="bloqueado.jpg"
Content-Type: image/jpeg

< ./images/leno.jpg
--WebAppBoundary--


### ==========================================
### 3. SISTEMA DE LANCES (Requer Allowed = true)
### ==========================================

### 🔴 TENTATIVA FALHA: Dono dando lance no próprio anúncio (Usuário 1 no Anúncio 1)
POST {{baseUrl}}/auctions/1/bids/place
X-User-Id: {{user1_id}}
X-User-Name: {{user1_name}}
X-User-Email: {{user1_email}}
X-User-Allowed: {{user1_allowed}}
Content-Type: application/json

{
  "bidAmount": 15.00
}


### 🔵 Lance Válido: Usuário 2 dá lance no Anúncio 1
POST {{baseUrl}}/auctions/3/bids/place
X-User-Id: {{user2_id}}
X-User-Name: {{user2_name}}
X-User-Email: {{user2_email}}
X-User-Allowed: {{user2_allowed}}
Content-Type: application/json

{
  "bidAmount": 50.00
}


### 🔴 TENTATIVA FALHA: Lance com incremento inválido (< 5%)
POST {{baseUrl}}/auctions/1/bids/place
X-User-Id: {{user2_id}}
X-User-Name: {{user2_name}}
X-User-Email: {{user2_email}}
X-User-Allowed: {{user2_allowed}}
Content-Type: application/json

{
  "bidAmount": 51.00
}


### 🔴 TENTATIVA FALHA: Usuário Bloqueado tentando dar lance (Deve barrar na regra do Allowed)
POST {{baseUrl}}/auctions/1/bids/place
X-User-Id: {{user3_id}}
X-User-Name: {{user3_name}}
X-User-Email: {{user3_email}}
X-User-Allowed: {{user3_allowed}}
Content-Type: application/json

{
  "bidAmount": 5000.00
}


### ==========================================
### 4. GERENCIAMENTO (Ignora Allowed, checa posse)
### ==========================================

### 🟠 Deletar próprio anúncio (Usuário 1 deleta Anúncio 1)
DELETE {{baseUrl}}/auctions/delete/2
X-User-Id: {{user1_id}}
X-User-Name: {{user1_name}}
X-User-Email: {{user1_email}}
X-User-Allowed: {{user1_allowed}}

### 🔴 TENTATIVA FALHA: Deletar anúncio de outro usuário (Usuário 2 tenta deletar Anúncio 1)
DELETE {{baseUrl}}/auctions/delete/1
X-User-Id: {{user2_id}}
X-User-Name: {{user2_name}}
X-User-Email: {{user2_email}}
X-User-Allowed: {{user2_allowed}}